---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
  namespace: default
spec:
  profile:
    displayName: Alice Anderson
    email: alice@example.com
    picture: https://api.dicebear.com/9.x/identicon/svg?seed=alice
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob
  namespace: default
spec:
  profile:
    displayName: Bob Brown
    email: bob@example.com
    picture: https://api.dicebear.com/9.x/identicon/svg?seed=bob
  memberOf: []
