name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - run: corepack enable

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type-check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Format check
        run: yarn format:check

      - name: Build
        run: yarn build
